@apiUrl=http://localhost:3000/api/items
@apiUrl2=http://localhost:3000/api/categories

### Get all items
GET {{apiUrl}}

### Get all categeories
GET {{apiUrl2}}

### Get item by item number
GET {{apiUrl}}/1

### Create new item
POST {{apiUrl}}
Content-Type: application/json

{
  "ItemNumber": 2,
  "ItemName": "Item2",
  "Description": "This is item 2",
  "Available": "Y",
  "Damaged": "N",
  "Category": "Category2",
  "Picture": null
}


### Create new item
POST {{apiUrl2}}
Content-Type: application/json

{
  "name": "Category2"
}

### Update item
PUT {{apiUrl}}/2
Content-Type: application/json

{
  "ItemName": "Updated Item2",
  "Description": "This is updated item 2",
  "Available": "N",
  "Damaged": "Y",
  "Category": "Updated Category2",
  "Picture": null
}

### Delete item
DELETE {{apiUrl}}/2